### ISSUE TITLE
Default value for Endpoint.produces is confusing

### ISSUE THREAD

**Issue by abingham** [Parquery/swagger-to#121]
I might be misinterpreting the OAS, but I think the default value for `Endpoint.produces` is incorrect. If an operation in the spec does not specify a `produces` field, swagger-to gives that endpoint a value of an empty list. I *think* this is incorrect because I later have to interpret that empty list as overriding the global `produces` field.

[In the OAS spec's discussion of `produces`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-5) it says "An empty value MAY be used to clear the global definition". But if I'm getting an empty list when the user doesn't specify `produces` for an endpoint, then I can't differentiate between a) an override and b) not having a `produces` field.

Is there a way to differentiate between these two cases, or is this a hole in swagger-to? Or do I just misunderstand things?

**Comment by mristin** [comment]
Hi @abingham ,
I think it is a hole in swagger-to. If I make `produces` optional field (*i.e.*, it is `None` if not specified), that would work, correct?

Could you post an example spec that you would like to process so that I can test against it?

**Comment by abingham** [comment]
I agree that `produces` should be optional for an endpoint. But if the user doesn't specify `produces` for an endpoint, it might be more useful to set it to the global `produces` rather than `None`. That way, when I need to know what an endpoint produces, I can always just look at its `produces` value rather than having to optionally look at the global value.

This would mean, of course, that it's not possible to tell when an endpoint didn't have a `produces` field specified. But I can't think of a situation where I would care about that.

**Comment by mristin** [comment]
@abingham could you write 2-3 specs that I could use as unit tests (so that we can also inspect the results together)?

Should `produces` be resolved at the IR level or when generating the code?

**Comment by abingham** [comment]
> could you write 2-3 specs

Do you mean the more cases in the `tests/cases/intermediate` directory? Sure, I can probably put something together. How do I create the `endpoints.json` file? I tried using `json.dump` on an `Endpoint` but was told that `Endpoint`s are not JSON serializable.

> Should produces be resolved at the IR level or when generating the code?

I assume that it should be resolved in the IR. I'm working on writing a code generator, though, so maybe I'm not thinking of the big picture.

**Comment by mristin** [comment]
> could you write 2-3 specs

> Do you mean the more cases in the tests/cases/intermediate directory?

I was actually thinking of swagger.yaml to avoid ambiguities. Then we would discuss the generated output.

It actually makes sense to resolve it already at IR level - I couldn't think of any case where the generator would need to know the difference.

**Comment by abingham** [comment]
Ok, here are three that I think cover the main cases. First, a global `produces` with no `produces` specified for the endpoint:
```
basePath: /
consumes:
- application/json
produces:
- application/json
info:
  description: Test
  title: Test
  version: '1.0'
paths:
  /:
    get:
      operationId: get
      responses:
        '200':
          description: Success
swagger: '2.0'
tags:
  - description: Test API
    name: API 
```

Here's the same but with the endpoint specifying a different mime type:
```
basePath: /
consumes:
- application/json
produces:
- application/json
info:
  description: Test
  title: Test
  version: '1.0'
paths:
  /:
    get:
      produces: 
      - image/png
      operationId: get
      responses:
        '200':
          description: Success
swagger: '2.0'
tags:
  - description: Test API
    name: API 
```
And here's one where the endpoint explicitly clears the produces field by using an empty list:
```
basePath: /
consumes:
- application/json
produces:
- application/json
info:
  description: Test
  title: Test
  version: '1.0'
paths:
  /:
    get:
      produces: []
      operationId: get
      responses:
        '200':
          description: Success
swagger: '2.0'
tags:
  - description: Test API
    name: API 
```

**Comment by mristin** [comment]
Thanks, @abingham! I'll try to have something implemented this weekend.

**Comment by mristin** [comment]
@abingham let's wait with a new version till you finish your Elm generator. I anticipate more issues :).
