### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by abingham** [Parquery/swagger-to#124]
Are there plans to make a new release of swagger-to? I've got projects that depend on it, but they currently only work with the master branch.

**Comment by mristin** [comment]
Hi @abingham,
Please apologize for the delay. This was on my todo list, but just slipped in priority. I've just released a new version; it should be on PyPI in a minute.

**Comment by mristin** [comment]
I'll close the issue for now. If there are problems with the version 4.1.0, please create a new issue.

**Comment by abingham** [comment]
Thanks! Everything seems to work.
