### ISSUE TITLE
definitions properties referenced itself will cause  maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by stevenxuwoss** [Parquery/swagger-to#129]
some like menu and child menu, to find definitions will cause  maximum recursion depth exceeded while calling a Python object

**Comment by stevenxuwoss** [comment]
the paser typeof and get typeof have same issues

**Comment by mristin** [comment]
Hi @stevenxuwoss ,
Thanks for the report! Could you please post a minimal schema that reproduces the bug so that I can add it to the regression tests?

**Comment by stevenxuwoss** [comment]
some like from java objects
`
JsonArray:
    type: object
    discriminator: ''
    properties:
      asBigDecimal:
        type: number
      asBigInteger:
        type: integer
      asBoolean:
        type: boolean
      asByte:
        type: integer
        format: int32
        minimum: -128
        maximum: 127
      asCharacter:
        type: string
      asDouble:
        type: number
        format: double
      asFloat:
        type: number
        format: float
      asInt:
        type: integer
        format: int32
      asJsonArray:
        $ref: '#/definitions/JsonArray'
      asJsonNull:
        $ref: '#/definitions/JsonNull'
      asJsonObject:
        $ref: '#/definitions/JsonObject'
      asJsonPrimitive:
        $ref: '#/definitions/JsonPrimitive'
      asLong:
        type: integer
        format: int64
      asNumber:
        $ref: '#/definitions/Number'
      asShort:
        type: integer
        format: int32
      asString:
        type: string
      jsonArray:
        type: boolean
      jsonNull:
        type: boolean
      jsonObject:
        type: boolean
      jsonPrimitive:
        type: boolean
    title: JsonArray
    description: ''
`
or some like items type is same , it will recursion to itself
`  Service:
    type: object
    discriminator: ''
    properties:
      currentValue:
        type: string
      identifier:
        type: string
      inputData:
        type: array
        items:
          $ref: '#/definitions/Service'`

**Comment by mristin** [comment]
Hi @stevenxuwoss ,
Please apologize for the delay on my side. I am very busy at the moment (probably whole October 2021). How important is this feature to you and what about your timeline -- is it critical and when would you need it latest?

**Comment by stevenxuwoss** [comment]
@mristin thanks for your reply！I use swagger to and auto gen the python api to test our project and i did some workaround and  not block my work yet.
