### ISSUE TITLE
Error on definitions ID

### ISSUE THREAD

**Issue by RyanAquino** [Parquery/swagger-to#85]
Getting an error on setting ID to integer, it only accepts string. I am not sure if this is intended

`definitions:
  Project:
    required:
      - "name"
      - "created_by"
    type: object
    properties:
      id:
        title: "ID"
        type: integer
        readOnly: true`

**Comment by mristin** [comment]
Hi @RyanAquino ,
Could you please post the whole schema (or a reduced one that is at least accepted by editor.swagger.io) together with the exact error code?

**Comment by RyanAquino** [comment]
Hi @mristin ,

I have found a quick workaround. I need to define `format:int64`  for it to work without errors.

**Comment by mristin** [comment]
Good, I'll close the issue.
