### ISSUE TITLE
swagger_to_py_client.py generates invalid function names

### ISSUE THREAD

**Issue by falzm** [Parquery/swagger-to#88]
Hi,

When using `swagger_to_py_client.py` the resulting generated code ends up containing invalid code where dashes (`-` are not filtered out. For example, from our OpenAPI Spec our `operationId` are formatted in _dash-case_:

```console
$ grep operationId oas.yaml | grep snapshot
      operationId: create-snapshot
      operationId: list-snapshots
      operationId: delete-snapshot
      operationId: get-snapshot
      operationId: get-export-snapshot
      operationId: export-snapshot

$ swagger_to_py_client.py --swagger_path oas.yaml --outpath test.py
Generated python client code in: test.py

$ grep 'def .*snapshot.*' test.py
    def create-snapshot(
    def get-export-snapshot(
    def export-snapshot(
    def delete-snapshot(
    def get-snapshot(
    def list-snapshots(self) -> bytes:
```

After digging a little it seems that this is not supposed to happen, as your code generation templates are calling a formatting function [`snake_case()`](https://github.com/Parquery/swagger-to/blob/master/swagger_to/__init__.py#L252) is which supposed to prevent this, but for some reason it looks like that's not happening...

Version used:

```
$ pip freeze | grep swagger-to
swagger-to==4.0.0
```

**Comment by falzm** [comment]
I did a bit more digging, and turns out the operation ID is not formatted through the `snake_case()` method mentioned above. The following change fixes the issue:

```diff
--- /a/swagger_to/py_client.py	2020-09-07 16:06:30.000000000 +0200
+++ /b/swagger_to/py_client.py	2020-09-07 16:38:21.000000000 +0200
@@ -310,7 +310,7 @@
     req = Request()
     req.description = endpoint.description
     req.method = endpoint.method
-    req.operation_id = endpoint.operation_id
+    req.operation_id = swagger_to.snake_case(endpoint.operation_id)
     req.path = endpoint.path

     ##
```

If you're OK with this resolution, I can push a PR to this project.

**Comment by mristin** [comment]
Hi @falzm !
Thanks for reporting the issue! Let me have a closer look at it.

**Comment by mristin** [comment]
Hi @falzm ,
I took your suggestion and made it a bit more robust to future maintenance. Before I publish a new patch version, could you please see if you have any other breaking Swagger specs in the code base? One error is often a good indicator for the next one :-).

**Comment by falzm** [comment]
Hi @mristin thank you for the reactivity, however I'm not sure if I'm doing wrong or if something is still missing, as I still get the same bogus output when running the test from the repository tip:

```console
$ git clone https://github.com/Parquery/swagger-to.git
$ cd swagger-to
swagger-to$ git log -1
commit 12dc582f74da706b1cb8334704b4fa1e22576ad2 (HEAD -> master, origin/master, origin/HEAD)
Author: Marko Ristin <marko.ristin@gmail.com>
Date:   Mon Sep 7 20:19:10 2020 +0200

    dashes in operation IDs supported in py_client (#89)

    There are specs in the wild that use dashes in the operation IDs.
    While uncommon, there is no reason why code generated by py_client
    should not handle these cases correctly. This patch lets the function
    names be determined by the snake case of the operation ID instead of
    the vanilla value.

    Fixes #88.

# The "snapshots.oas.yaml" can be found here: https://gist.github.com/falzm/5e36c75957da916a041f46171d4319a1
$ PYTHONPATH=. python bin/swagger_to_py_client.py --swagger_path=$HOME/Desktop/snapshots.oas.yaml --outpath test.py
Generated python client code in: test.py

$ grep 'def ' test.py
    def __init__(self, url_prefix: str, auth: Optional[requests.auth.AuthBase] = None) -> None:
    def list_snapshots(self) -> bytes:
    def delete-snapshot(
    def get-snapshot(
    def get-export-snapshot(
    def export-snapshot(
```

**Comment by falzm** [comment]
Looking closer, we can see that only the first function name is correct (`list_snapshots()`), all the following function names don't seem to be affected by the formatting.

**Comment by mristin** [comment]
Thanks, @falzm ! The test was obviously too narrow. I'll try to fix it tonight.

**Comment by mristin** [comment]
Hi @falzm ,
Could you please double-check that the issue has been resolved and reopen the issue if there are still bugs? I tried with the specs you mentioned (in https://gist.github.com/falzm/5e36c75957da916a041f46171d4319a1) and the code looked now correct to me.

**Comment by falzm** [comment]
@mristin I confirm that it now works as expected, thank you!
