### ISSUE TITLE
Deserialisation fails on non-required fields if `None` is provided.

### ISSUE THREAD

**Issue by JarkoDubbeldam** [Parquery/swagger-to#95]
I'm using this library to create a Python client for an API that returns a nullable string in its response. When null, the response looks like so: `{"NullableString": null}`, or `obj = {"NullableString": None}` as Python dict.

The deserialization code appears to expect null fields to be completely missing, instead of being explicitly nulled, and throws expecting a `str`.

## Swagger example

```
{
    "swagger": "2.0",
    "basePath": "/",
    "paths": {
    },
    "info": {
        "title": "",
        "version": "",
        "description": ""
    },
    "produces": [
        "application/json"
    ],
    "consumes": [
        "application/json"
    ],
    "definitions": {
        "SomeResponse": {
            "properties": {
                "NullableString": {
                    "type": "string",
                    "description": "blabla"
                }
            },
            "type": "object"
        }
    },
    "responses": {
        "ParseError": {
            "description": "When a mask can't be parsed"
        },
        "MaskError": {
            "description": "When any error occurs on mask"
        }
    }
}

```
## Python example

```
from client import some_response_from_obj
obj = {"NullableString": None}
some_response_from_obj(obj) #throws
```

**Comment by JarkoDubbeldam** [comment]
The serialisation code in `from_obj` doesn't appear to do any null-checking on its own. So I think the easiest way to adjust this would be to add a null check to the class-specific deserialisation code generated here: https://github.com/Parquery/swagger-to/blob/2b6a8c20faf807cdd271069c18c8d53f8106f1e0/swagger_to/py_client.py#L879

**Comment by mristin** [comment]
Hi @JarkoDubbeldam ,
As far as I am aware, JSON does not support `null`?

If you make the property optional, it should work as expected?

**Comment by mristin** [comment]
Before I dig deeper, could you please review this test case for me:
https://github.com/Parquery/swagger-to/tree/master/tests/cases/py_client/object_with_optional_properties
?

Is it the same case as yours?

**Comment by mristin** [comment]
Sorry, now I got it. You would like to have the object serialized to JSON without the field when that field is `None` in Python. There would be a check like something in the line of `if attr in obj and obj[attr] is not None`. Did I get that right?

**Comment by JarkoDubbeldam** [comment]
Exactly.

**Comment by JarkoDubbeldam** [comment]
I checked the testcase, output from `swagger_to_py_client.py` is the same (bar the session code that probably hasn't been released yet). The behaviour is the same. Trying to deserialise the json `{"product_id":null}` results in an error from `test_object_from_obj`.

**Comment by JarkoDubbeldam** [comment]
The behaviour when serialising to json doesn't seem particularly affected, since the generated code omits any `null`/`None` fields, which is fine. The problem is when deserialising responses, since I can't easily control whether the incoming json has explicit `null` fields, or omits them altogether.

**Comment by mristin** [comment]
@JarkoDubbeldam thanks! I'll try to produce a fix tonight.

**Comment by JarkoDubbeldam** [comment]
I think what you suggested

> `if attr in obj and obj[attr] is not None`

or `if obj.get(attr) is not None` should do the trick. That fixes it for me at least.

Thanks for looking at it :)

**Comment by mristin** [comment]
Hi @JarkoDubbeldam ,
Could you please review PR for me: #98 ? In particular, could you please double-check whether the client looks as you expected:
https://github.com/Parquery/swagger-to/pull/98/files#diff-761cbc4ba5ac3ea018485cbf88e1e01f

and whether the unit tests actually test the correct behavior:
https://github.com/Parquery/swagger-to/pull/98/files#diff-67d7b587f6ada83edaab950b6ca09567
?

Thanks in advance!

**Comment by JarkoDubbeldam** [comment]
Looks good to me. I'm not quite sure what the exact details were of the template that was changed, but the output looks good, both in the testcases as when I ran it on my own swaggerfile.

**Comment by mristin** [comment]
@JarkoDubbeldam thanks! Let's wait for a week to see if there are more issues before I bump the patch version.
